[services.yt-token-service]
[services.yt-token-service.build]
dockerfilePath = "Dockerfile.yt-token"

[services.yt-token-service.deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
